import Head from 'next/head'
import Certifications from '../components/Certifications'
import Education from '../components/Education'
import Experiance from '../components/Experiance'
import Header from '../components/Header'
import Languages from '../components/Languages'
import Profile from '../components/Profile'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="px-1 sm:px-[10%] py-14 font-coolvetica" >
      <Head>
        <title>Badr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Profile/>
      <div id="Skills" className='scroll-my-24'>
       <Skills/>
      </div>
      <div id="Education" className='scroll-my-24'>
      <Education/>
      </div>
      <div id="Experiance" className='scroll-my-24'>
      <Experiance/>
      </div>
      <div id="Projects" className='scroll-my-24'>
      <Projects/>
      </div>
      <div id="Certifications" className='scroll-my-24'>
      <Certifications/>
      </div>
      <div id="Languages" className='scroll-my-24'>
       <Languages/>
      </div>
      
    </div>
  )
}
