import Head from 'next/head'
import React, { ReactElement } from 'react'
import Certifications from '../components/Certifications'
import ConatctMe from '../components/ConatctMe'
import Education from '../components/Education'
import Experiance from '../components/Experiance'
import Header from '../components/Header'
import Languages from '../components/Languages'
import Profile from '../components/Profile'
import Projects from '../components/Projects'
import Skills from '../components/Skills'

export default function Home (): ReactElement {
  return (
    <div className="px-1 scroll-smooth sm:px-[10%] py-14 font-coolvetica">
      <Head>
        <title>Badr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Profile />
      <div id="Skills" className="scroll-my-32">
        <Skills />
      </div>
      <div id="Education" className="scroll-my-32">
        <Education />
      </div>
      <div id="Experiance" className="scroll-my-32">
        <Experiance />
      </div>
      <div id="Projects" className="scroll-my-32">
        <Projects />
      </div>
      <div id="Certifications" className="scroll-my-32">
        <Certifications />
      </div>
      <div id="Languages" className="scroll-my-32">
        <Languages />
      </div>
      <div id="ConatctMe" className="scroll-my-32">
        <ConatctMe />
      </div>
    </div>
  )
}
